### ISSUE TITLE
Execution failed for task ':webpackDevServerOpenBrowser'.

### ISSUE THREAD

**Issue by AsimShakour** [cfnz/muirwik-starterapp#5]
Thanks for the share. I am getting this issue (

Would appreciate help on:

15:57:30.822 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
15:57:30.822 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 6: released lock on root.1
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':webpackDevServerOpenBrowser'.
15:57:30.822 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > A problem occurred starting process 'command 'C:\Users\AsimShakour\muirwik-starterapp/node_modules/.bin/webpack-dev-server''

========================================
Things I have -->
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1957M
Cores: 8
Registry: 
Non-Bundled Plugins: io.ktor.intellij.plugin, org.intellij.scala, training, 
Also have - Java\jdk1.8.0_221\).

**Comment by cfnz** [comment]
OK, managed to replicate the issue on a Windows box here...

If you are stuck here, you can just run that same command that it complains about from the command prompt, the default params will start the webpack server but won't open a browser, so just navigate to localhost:8080... there is not much to see there, just a barebones starter app...

**Comment by cfnz** [comment]
Resolved this some time ago
